### ISSUE TITLE
Feature Request: extract the version of eagle

### ISSUE THREAD

**Issue by JacobChrist** [I2SE/eagle-bom.py#10]
Include a command line switch to extract the version of eagle used to generate the schematic or board.

Also, if the file feed to the program is not an eagle file the program should indicate that it cannot determine file type.

**Comment by ch-aurich** [comment]
I am not sure why you would need this - however, it would be quite easy, so I would add it if it is needed.

Could you please explain the use for this feature?

What I could imagine is to add an header to the bom to document how it was generated (what was the base file, what parameters were used, what version of the eagle-bom.py script, etc.) - the eagle version could easily be added in this header too.

**Comment by JacobChrist** [comment]
KiCAD and Eagle files both end in .sch, I need a way to detect if the file is KiCAD or eagle.  Could be a separate tool.

**Comment by ch-aurich** [comment]
The above commit should fix this issue, please verify it and reopen this issue if there is any problem.
