### ISSUE TITLE
Feature Request: Ability to take sch or brd files as input from stdio

### ISSUE THREAD

**Issue by JacobChrist** [I2SE/eagle-bom.py#11]
This is not a feature I need, but it could be useful for piping files around on the command line.

**Comment by ch-aurich** [comment]
I would use stdin/stdout by default but use CLI arguments to input/output files as well. Is this what you think will be ok?

**Comment by JacobChrist** [comment]
What do you mean by CLI?

What I was thinking was that it would be nice to pipe the output to awk or
sed for column addition, deletion or rearranging. This would prevent
creating temp files that might get clobbered if named incorrectly.

I have not had much time to work on this project lately. I teach college
part time and I am in the middle of a class now.  I hope to pick it back up
in a couple of weeks when I have reviewed all of the material for my class
for the semester.

Jacob

**Comment by ch-aurich** [comment]
With CLI I mean command line interface. 

What I want to do is to support stdin and stdout when no parameters --brd --sch and --csv are set - but I would not remove passing filenames as arguments completely.

**Comment by JacobChrist** [comment]
Agreed, don't remove completely.
