### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ch-aurich** [I2SE/eagle-bom.py#15]
For further development I'd like to setup a license for this script. I'd like to use MIT.

There were changes from @JacobChrist - could you please confirm that you are ok with that?

**Comment by ch-aurich** [comment]
Received via private e-mail Jacob writes:
> MIT, BSD or Apache are some of my favorites.

So I will consider this as ACK to my request and put the code under MIT license.

**Comment by JacobChrist** [comment]
Yes, please do.

**Comment by ch-aurich** [comment]
solved by commit 324d6694fe46a52c7d9d1c5c96d99203b1895905
