### ISSUE TITLE
Test schematic blink1_v1a.sch not generating BOM

### ISSUE THREAD

**Issue by JacobChrist** [I2SE/eagle-bom.py#7]
I thought I had already posted this, but I can't find it (it was late and I was really tired).  I have more details now.  When I try to generate the BOM for this schematic I get an exception.  The exception come from the greek leter mu u'\xb5' being used to represent micro in micro farads of C2.

Traceback (most recent call last):
  File "eagle-bom.py/eagle-bom.py", line 430, in <module>
    main(sys.argv[1:])
  File "eagle-bom.py/eagle-bom.py", line 427, in main
    bom_creation(settings)
  File "eagle-bom.py/eagle-bom.py", line 354, in bom_creation
    settings['set_delimiter'])
  File "eagle-bom.py/eagle-bom.py", line 131, in write_part_list
    dict_writer.writerows(elements)
  File "C:\Python27\lib\csv.py", line 158, in writerows
    return self.writer.writerows(rows)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 2: ordinal not in range(128)

If I print out the the element I see this:

e={'DEVICE': 'C0603', 'PACKAGE': 'C0603', 'NAME': 'C2', 'VALUE': u'10\xb5F', 'DESCRIPTION': 'CAPACITOR, American symbol'}

This happens when the CSV file is being written.  I'm not quite sure why it happening and if it is my environment or a code issue.  I'm running Python 2.7.11 in Windows 10.

Jacob

**Comment by ch-aurich** [comment]
I think this should be fixed by merging #9dae02a30ab88da2e2b79bd3bb6f994d0bc67414
